//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi annotazione.
        /// </summary>
        internal static string btn_add_annotation {
            get {
                return ResourceManager.GetString("btn_add_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi category!.
        /// </summary>
        internal static string btn_add_category {
            get {
                return ResourceManager.GetString("btn_add_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi code!.
        /// </summary>
        internal static string btn_add_code {
            get {
                return ResourceManager.GetString("btn_add_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi concept!.
        /// </summary>
        internal static string btn_add_concept {
            get {
                return ResourceManager.GetString("btn_add_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_confirm_import {
            get {
                return ResourceManager.GetString("btn_confirm_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        internal static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna Annotazioni.
        /// </summary>
        internal static string btn_edit_annotation {
            get {
                return ResourceManager.GetString("btn_edit_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primo.
        /// </summary>
        internal static string btn_goto_first {
            get {
                return ResourceManager.GetString("btn_goto_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo.
        /// </summary>
        internal static string btn_goto_last {
            get {
                return ResourceManager.GetString("btn_goto_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa CSV.
        /// </summary>
        internal static string btn_import_csv {
            get {
                return ResourceManager.GetString("btn_import_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa file CSV.
        /// </summary>
        internal static string btn_import_csv_file {
            get {
                return ResourceManager.GetString("btn_import_csv_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova categorization.
        /// </summary>
        internal static string btn_new_categorization {
            get {
                return ResourceManager.GetString("btn_new_categorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo category scheme.
        /// </summary>
        internal static string btn_new_categoryscheme {
            get {
                return ResourceManager.GetString("btn_new_categoryscheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova codelist.
        /// </summary>
        internal static string btn_new_codelist {
            get {
                return ResourceManager.GetString("btn_new_codelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo concept scheme.
        /// </summary>
        internal static string btn_new_conceptscheme {
            get {
                return ResourceManager.GetString("btn_new_conceptscheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Dataflow.
        /// </summary>
        internal static string btn_new_dataflow {
            get {
                return ResourceManager.GetString("btn_new_dataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi KeyFamily.
        /// </summary>
        internal static string btn_new_keyFamily {
            get {
                return ResourceManager.GetString("btn_new_keyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona un elemento.
        /// </summary>
        internal static string btn_open_grid_div {
            get {
                return ResourceManager.GetString("btn_open_grid_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona una categoria.
        /// </summary>
        internal static string btn_open_tree_div {
            get {
                return ResourceManager.GetString("btn_open_tree_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALVA!.
        /// </summary>
        internal static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALVA.
        /// </summary>
        internal static string btn_save_dataflow {
            get {
                return ResourceManager.GetString("btn_save_dataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna category.
        /// </summary>
        internal static string btn_update_category {
            get {
                return ResourceManager.GetString("btn_update_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna code!.
        /// </summary>
        internal static string btn_update_code {
            get {
                return ResourceManager.GetString("btn_update_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna concept!.
        /// </summary>
        internal static string btn_update_concept {
            get {
                return ResourceManager.GetString("btn_update_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna dataflow.
        /// </summary>
        internal static string btn_update_dataflow {
            get {
                return ResourceManager.GetString("btn_update_dataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string btn_upload_file {
            get {
                return ResourceManager.GetString("btn_upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;aggiunta dell&apos;attributo..
        /// </summary>
        internal static string err_add_attribute {
            get {
                return ResourceManager.GetString("err_add_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;aggiunta della dimensione..
        /// </summary>
        internal static string err_add_dimension {
            get {
                return ResourceManager.GetString("err_add_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;aggiunta del gruppo..
        /// </summary>
        internal static string err_add_group {
            get {
                return ResourceManager.GetString("err_add_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi una dimensione normale.
        /// </summary>
        internal static string err_add_normal_dimension {
            get {
                return ResourceManager.GetString("err_add_normal_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi una dimensione temporale..
        /// </summary>
        internal static string err_add_time_dimension {
            get {
                return ResourceManager.GetString("err_add_time_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un stato di assegnazione..
        /// </summary>
        internal static string err_assign_status_empty {
            get {
                return ResourceManager.GetString("err_assign_status_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un livello di attaccamento..
        /// </summary>
        internal static string err_attachment_level_empty {
            get {
                return ResourceManager.GetString("err_attachment_level_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un livello di attaccamento per l&apos;attributo..
        /// </summary>
        internal static string err_attribute_attachment_level_empty {
            get {
                return ResourceManager.GetString("err_attribute_attachment_level_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almeno un elemento deve essere selezionato!.
        /// </summary>
        internal static string err_at_least_one_row {
            get {
                return ResourceManager.GetString("err_at_least_one_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;inserimento della categoria.
        /// </summary>
        internal static string err_category_insert {
            get {
                return ResourceManager.GetString("err_category_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;aggiornamento della categoria.
        /// </summary>
        internal static string err_category_update {
            get {
                return ResourceManager.GetString("err_category_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un errore è stato riscontrato nella aggiunta del code.
        /// </summary>
        internal static string err_code_insert {
            get {
                return ResourceManager.GetString("err_code_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione Code ID usato come Parent ID.
        /// </summary>
        internal static string err_code_is_parent {
            get {
                return ResourceManager.GetString("err_code_is_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un riferimento allo schema del concetto..
        /// </summary>
        internal static string err_conceptscheme_ref_empty {
            get {
                return ResourceManager.GetString("err_conceptscheme_ref_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;inserimento del concetto.
        /// </summary>
        internal static string err_concept_insert {
            get {
                return ResourceManager.GetString("err_concept_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept ID utilizzato come parent..
        /// </summary>
        internal static string err_concept_is_parent {
            get {
                return ResourceManager.GetString("err_concept_is_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un riferimento al concetto..
        /// </summary>
        internal static string err_concept_ref_empty {
            get {
                return ResourceManager.GetString("err_concept_ref_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;aggiornamento del concetto.
        /// </summary>
        internal static string err_concept_update {
            get {
                return ResourceManager.GetString("err_concept_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La data iniziale non può essere maggiore della data finale!.
        /// </summary>
        internal static string err_date_diff {
            get {
                return ResourceManager.GetString("err_date_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correggere data iniziale.
        /// </summary>
        internal static string err_date_from_format {
            get {
                return ResourceManager.GetString("err_date_from_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correggere data finale.
        /// </summary>
        internal static string err_date_to_format {
            get {
                return ResourceManager.GetString("err_date_to_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;eliminazione dell&apos;attributo..
        /// </summary>
        internal static string err_delete_attribute {
            get {
                return ResourceManager.GetString("err_delete_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;eliminazione della dimensione..
        /// </summary>
        internal static string err_delete_dimension {
            get {
                return ResourceManager.GetString("err_delete_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell&apos;eliminazione del gruppo..
        /// </summary>
        internal static string err_delete_goup {
            get {
                return ResourceManager.GetString("err_delete_goup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi avere almeno una dimensione..
        /// </summary>
        internal static string err_dimension_count {
            get {
                return ResourceManager.GetString("err_dimension_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non e&apos; possibile selezionare tutte le dimensioni.
        /// </summary>
        internal static string err_dimension_count_out {
            get {
                return ResourceManager.GetString("err_dimension_count_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare la Key Family.
        /// </summary>
        internal static string err_dsd_ref_empty {
            get {
                return ResourceManager.GetString("err_dsd_ref_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione non consentita.
        /// </summary>
        internal static string err_generic_category_order {
            get {
                return ResourceManager.GetString("err_generic_category_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un livello di attaccamento per il gruppo..
        /// </summary>
        internal static string err_group_attachment_level_empty {
            get {
                return ResourceManager.GetString("err_group_attachment_level_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID inserito già presente.
        /// </summary>
        internal static string err_id_exist {
            get {
                return ResourceManager.GetString("err_id_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immettere ID valido.
        /// </summary>
        internal static string err_id_format {
            get {
                return ResourceManager.GetString("err_id_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID del gruppo non valido.
        /// </summary>
        internal static string err_id_group_format {
            get {
                return ResourceManager.GetString("err_id_group_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immettere almeno un Name.
        /// </summary>
        internal static string err_list_name_format {
            get {
                return ResourceManager.GetString("err_list_name_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserire almeno un valore.
        /// </summary>
        internal static string err_list_value_format {
            get {
                return ResourceManager.GetString("err_list_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato selezionato un file dati!.
        /// </summary>
        internal static string err_no_file_uploaded {
            get {
                return ResourceManager.GetString("err_no_file_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID non appartenente alla lista.
        /// </summary>
        internal static string err_parent_id_not_found {
            get {
                return ResourceManager.GetString("err_parent_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un concetto per la misura principale..
        /// </summary>
        internal static string err_primary_measure_empty {
            get {
                return ResourceManager.GetString("err_primary_measure_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel salvataggio della DSD..
        /// </summary>
        internal static string err_save_dsd {
            get {
                return ResourceManager.GetString("err_save_dsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore!.
        /// </summary>
        internal static string err_title {
            get {
                return ResourceManager.GetString("err_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immettere titolo valido.
        /// </summary>
        internal static string err_title_format {
            get {
                return ResourceManager.GetString("err_title_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immettere type valido.
        /// </summary>
        internal static string err_type_format {
            get {
                return ResourceManager.GetString("err_type_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immettere URI valido.
        /// </summary>
        internal static string err_uri_format {
            get {
                return ResourceManager.GetString("err_uri_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immettere Versione valida..
        /// </summary>
        internal static string err_version_format {
            get {
                return ResourceManager.GetString("err_version_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        internal static string lbl_add {
            get {
                return ResourceManager.GetString("lbl_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Annotazioni.
        /// </summary>
        internal static string lbl_add_annotation {
            get {
                return ResourceManager.GetString("lbl_add_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi category.
        /// </summary>
        internal static string lbl_add_category {
            get {
                return ResourceManager.GetString("lbl_add_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi code.
        /// </summary>
        internal static string lbl_add_code {
            get {
                return ResourceManager.GetString("lbl_add_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi concept.
        /// </summary>
        internal static string lbl_add_concept {
            get {
                return ResourceManager.GetString("lbl_add_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi descrizione.
        /// </summary>
        internal static string lbl_add_description {
            get {
                return ResourceManager.GetString("lbl_add_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi dimensione.
        /// </summary>
        internal static string lbl_add_dimension {
            get {
                return ResourceManager.GetString("lbl_add_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi gruppo.
        /// </summary>
        internal static string lbl_add_group {
            get {
                return ResourceManager.GetString("lbl_add_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi name.
        /// </summary>
        internal static string lbl_add_name {
            get {
                return ResourceManager.GetString("lbl_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Testo.
        /// </summary>
        internal static string lbl_add_text {
            get {
                return ResourceManager.GetString("lbl_add_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenzia.
        /// </summary>
        internal static string lbl_agency {
            get {
                return ResourceManager.GetString("lbl_agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotazioni.
        /// </summary>
        internal static string lbl_annotation {
            get {
                return ResourceManager.GetString("lbl_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artefatto.
        /// </summary>
        internal static string lbl_artefact {
            get {
                return ResourceManager.GetString("lbl_artefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Artefatto.
        /// </summary>
        internal static string lbl_artefact_type {
            get {
                return ResourceManager.GetString("lbl_artefact_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributi.
        /// </summary>
        internal static string lbl_attribute {
            get {
                return ResourceManager.GetString("lbl_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementi disponibili.
        /// </summary>
        internal static string lbl_available_items_list {
            get {
                return ResourceManager.GetString("lbl_available_items_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artefatti disponibili.
        /// </summary>
        internal static string lbl_available_structures_list {
            get {
                return ResourceManager.GetString("lbl_available_structures_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        internal static string lbl_back {
            get {
                return ResourceManager.GetString("lbl_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla spostamento.
        /// </summary>
        internal static string lbl_cancel_move_category {
            get {
                return ResourceManager.GetString("lbl_cancel_move_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string lbl_categories {
            get {
                return ResourceManager.GetString("lbl_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorization.
        /// </summary>
        internal static string lbl_categorization {
            get {
                return ResourceManager.GetString("lbl_categorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice.
        /// </summary>
        internal static string lbl_category_order {
            get {
                return ResourceManager.GetString("lbl_category_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Scheme.
        /// </summary>
        internal static string lbl_category_scheme {
            get {
                return ResourceManager.GetString("lbl_category_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Scheme disponibili.
        /// </summary>
        internal static string lbl_category_scheme_list {
            get {
                return ResourceManager.GetString("lbl_category_scheme_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist.
        /// </summary>
        internal static string lbl_codelist {
            get {
                return ResourceManager.GetString("lbl_codelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist.
        /// </summary>
        internal static string lbl_codelsit {
            get {
                return ResourceManager.GetString("lbl_codelsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes.
        /// </summary>
        internal static string lbl_codes {
            get {
                return ResourceManager.GetString("lbl_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Codificata.
        /// </summary>
        internal static string lbl_code_rappresentation {
            get {
                return ResourceManager.GetString("lbl_code_rappresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concetto.
        /// </summary>
        internal static string lbl_concept {
            get {
                return ResourceManager.GetString("lbl_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepts.
        /// </summary>
        internal static string lbl_concepts {
            get {
                return ResourceManager.GetString("lbl_concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riferimento al concetto.
        /// </summary>
        internal static string lbl_concept_reference {
            get {
                return ResourceManager.GetString("lbl_concept_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Scheme.
        /// </summary>
        internal static string lbl_concept_scheme {
            get {
                return ResourceManager.GetString("lbl_concept_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il cambiamento della lingua comportarà la perdita dei dati non salvati.\nContinuare senza salvare?.
        /// </summary>
        internal static string lbl_confirm_change_lang {
            get {
                return ResourceManager.GetString("lbl_confirm_change_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma spostamento.
        /// </summary>
        internal static string lbl_confirm_move_category {
            get {
                return ResourceManager.GetString("lbl_confirm_move_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File.
        /// </summary>
        internal static string lbl_csv_file {
            get {
                return ResourceManager.GetString("lbl_csv_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFlow.
        /// </summary>
        internal static string lbl_data_flow {
            get {
                return ResourceManager.GetString("lbl_data_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        internal static string lbl_delete {
            get {
                return ResourceManager.GetString("lbl_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina category.
        /// </summary>
        internal static string lbl_delete_category {
            get {
                return ResourceManager.GetString("lbl_delete_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicuro di voler eliminare l&apos;artefatto?.
        /// </summary>
        internal static string lbl_delete_question {
            get {
                return ResourceManager.GetString("lbl_delete_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        internal static string lbl_description {
            get {
                return ResourceManager.GetString("lbl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseleziona.
        /// </summary>
        internal static string lbl_deselect_category {
            get {
                return ResourceManager.GetString("lbl_deselect_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istat - Istituto nazionale di statistica EN.
        /// </summary>
        internal static string lbl_developer {
            get {
                return ResourceManager.GetString("lbl_developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via Cesare Balbo 16 00184 - Roma tel. +39 06 46731.
        /// </summary>
        internal static string lbl_developer_address {
            get {
                return ResourceManager.GetString("lbl_developer_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensioni.
        /// </summary>
        internal static string lbl_dimension {
            get {
                return ResourceManager.GetString("lbl_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo dimensione.
        /// </summary>
        internal static string lbl_dimension_type {
            get {
                return ResourceManager.GetString("lbl_dimension_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica.
        /// </summary>
        internal static string lbl_download {
            get {
                return ResourceManager.GetString("lbl_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica Artefatto.
        /// </summary>
        internal static string lbl_download_artefact {
            get {
                return ResourceManager.GetString("lbl_download_artefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizza download.
        /// </summary>
        internal static string lbl_download_title {
            get {
                return ResourceManager.GetString("lbl_download_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSD.
        /// </summary>
        internal static string lbl_dsd {
            get {
                return ResourceManager.GetString("lbl_dsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo export.
        /// </summary>
        internal static string lbl_export_type {
            get {
                return ResourceManager.GetString("lbl_export_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generale.
        /// </summary>
        internal static string lbl_general {
            get {
                return ResourceManager.GetString("lbl_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppi.
        /// </summary>
        internal static string lbl_group {
            get {
                return ResourceManager.GetString("lbl_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lbl_id {
            get {
                return ResourceManager.GetString("lbl_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artefatti importati.
        /// </summary>
        internal static string lbl_importated_aterfacts {
            get {
                return ResourceManager.GetString("lbl_importated_aterfacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa CSV.
        /// </summary>
        internal static string lbl_import_csv {
            get {
                return ResourceManager.GetString("lbl_import_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setta per spostamento.
        /// </summary>
        internal static string lbl_init_move_category {
            get {
                return ResourceManager.GetString("lbl_init_move_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizzata.
        /// </summary>
        internal static string lbl_is_final {
            get {
                return ResourceManager.GetString("lbl_is_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dettaglio.
        /// </summary>
        internal static string lbl_item_dettail {
            get {
                return ResourceManager.GetString("lbl_item_dettail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Family.
        /// </summary>
        internal static string lbl_key_family {
            get {
                return ResourceManager.GetString("lbl_key_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string lbl_lang {
            get {
                return ResourceManager.GetString("lbl_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua del file.
        /// </summary>
        internal static string lbl_language {
            get {
                return ResourceManager.GetString("lbl_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMX ISTAT Registry Message.
        /// </summary>
        internal static string lbl_message_title {
            get {
                return ResourceManager.GetString("lbl_message_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di righe.
        /// </summary>
        internal static string lbl_number_of_rows {
            get {
                return ResourceManager.GetString("lbl_number_of_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine.
        /// </summary>
        internal static string lbl_order {
            get {
                return ResourceManager.GetString("lbl_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        internal static string lbl_parent_category {
            get {
                return ResourceManager.GetString("lbl_parent_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Code.
        /// </summary>
        internal static string lbl_parent_code {
            get {
                return ResourceManager.GetString("lbl_parent_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Concept.
        /// </summary>
        internal static string lbl_parent_concept {
            get {
                return ResourceManager.GetString("lbl_parent_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attende prego....
        /// </summary>
        internal static string lbl_please_wait {
            get {
                return ResourceManager.GetString("lbl_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misura principale.
        /// </summary>
        internal static string lbl_primary_measure {
            get {
                return ResourceManager.GetString("lbl_primary_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare l&apos;attributo?.
        /// </summary>
        internal static string lbl_question_delete_attribute {
            get {
                return ResourceManager.GetString("lbl_question_delete_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare la dimensione?.
        /// </summary>
        internal static string lbl_question_delete_dimension {
            get {
                return ResourceManager.GetString("lbl_question_delete_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare il gruppo?.
        /// </summary>
        internal static string lbl_question_delete_group {
            get {
                return ResourceManager.GetString("lbl_question_delete_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione! Uscendo dalla pagina tutte le modifiche verranno perse..
        /// </summary>
        internal static string lbl_question_exit_page {
            get {
                return ResourceManager.GetString("lbl_question_exit_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona.
        /// </summary>
        internal static string lbl_select {
            get {
                return ResourceManager.GetString("lbl_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria selezionata.
        /// </summary>
        internal static string lbl_selected_category {
            get {
                return ResourceManager.GetString("lbl_selected_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento selezionato.
        /// </summary>
        internal static string lbl_selected_item {
            get {
                return ResourceManager.GetString("lbl_selected_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutti gli elementi.
        /// </summary>
        internal static string lbl_select_all_items {
            get {
                return ResourceManager.GetString("lbl_select_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona Codelist.
        /// </summary>
        internal static string lbl_select_codelist {
            get {
                return ResourceManager.GetString("lbl_select_codelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona Concetto.
        /// </summary>
        internal static string lbl_select_concept {
            get {
                return ResourceManager.GetString("lbl_select_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona file SDMX-ML.
        /// </summary>
        internal static string lbl_select_file_sdmxml {
            get {
                return ResourceManager.GetString("lbl_select_file_sdmxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona Key Family.
        /// </summary>
        internal static string lbl_select_keyfamily {
            get {
                return ResourceManager.GetString("lbl_select_keyfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia.
        /// </summary>
        internal static string lbl_send {
            get {
                return ResourceManager.GetString("lbl_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSD.
        /// </summary>
        internal static string lbl_set_dsd_for_dataflow {
            get {
                return ResourceManager.GetString("lbl_set_dsd_for_dataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istat Registry.
        /// </summary>
        internal static string lbl_site_title {
            get {
                return ResourceManager.GetString("lbl_site_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        internal static string lbl_structure {
            get {
                return ResourceManager.GetString("lbl_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stub.
        /// </summary>
        internal static string lbl_stub {
            get {
                return ResourceManager.GetString("lbl_stub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo.
        /// </summary>
        internal static string lbl_text {
            get {
                return ResourceManager.GetString("lbl_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolo.
        /// </summary>
        internal static string lbl_title {
            get {
                return ResourceManager.GetString("lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string lbl_type {
            get {
                return ResourceManager.GetString("lbl_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna category.
        /// </summary>
        internal static string lbl_update_category {
            get {
                return ResourceManager.GetString("lbl_update_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna code.
        /// </summary>
        internal static string lbl_update_code {
            get {
                return ResourceManager.GetString("lbl_update_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna concept.
        /// </summary>
        internal static string lbl_update_concept {
            get {
                return ResourceManager.GetString("lbl_update_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa Structure.
        /// </summary>
        internal static string lbl_upload_structure {
            get {
                return ResourceManager.GetString("lbl_upload_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string lbl_uri {
            get {
                return ResourceManager.GetString("lbl_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URN.
        /// </summary>
        internal static string lbl_urn {
            get {
                return ResourceManager.GetString("lbl_urn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valida da.
        /// </summary>
        internal static string lbl_valid_from {
            get {
                return ResourceManager.GetString("lbl_valid_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valida fino.
        /// </summary>
        internal static string lbl_valid_to {
            get {
                return ResourceManager.GetString("lbl_valid_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore.
        /// </summary>
        internal static string lbl_value {
            get {
                return ResourceManager.GetString("lbl_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione.
        /// </summary>
        internal static string lbl_version {
            get {
                return ResourceManager.GetString("lbl_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per poter accedere alla gestione Category è necessario inserire i dati relativi alla Category Scheme.
        /// </summary>
        internal static string missing_fields_for_category_scheme_message {
            get {
                return ResourceManager.GetString("missing_fields_for_category_scheme_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per salvare il dataflow è necessario aver selezionato la DSD.
        /// </summary>
        internal static string msg_at_least_one_dsd {
            get {
                return ResourceManager.GetString("msg_at_least_one_dsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;indice di ordinamento inserito non è valido!.
        /// </summary>
        internal static string msg_category_index_not_valid {
            get {
                return ResourceManager.GetString("msg_category_index_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spostamento annullato.
        /// </summary>
        internal static string msg_category_move_canceled {
            get {
                return ResourceManager.GetString("msg_category_move_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Scheme [ {0} - {1} - {2} ] aggiunto!&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string msg_category_scheme_imported {
            get {
                return ResourceManager.GetString("msg_category_scheme_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist [ {0} - {1} - {2} ] aggiunta!&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string msg_codelist_imported {
            get {
                return ResourceManager.GetString("msg_codelist_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Scheme [ {0} - {1} - {2} ] aggiunto!&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string msg_concept_scheme_imported {
            get {
                return ResourceManager.GetString("msg_concept_scheme_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data structure [ {0} - {1} - {2} ] aggiunto!&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string msg_data_structure_imported {
            get {
                return ResourceManager.GetString("msg_data_structure_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricamento in corso ....
        /// </summary>
        internal static string msg_loading {
            get {
                return ResourceManager.GetString("msg_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il nodo di destinazione!.
        /// </summary>
        internal static string msg_select_destination_node {
            get {
                return ResourceManager.GetString("msg_select_destination_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvenuti nel Registro della meta informazione dei dati statistici di diffusione dell&apos;istituto in formato SDMX.
        ///Per navigare la meta informazione è possibile utilizzare il menù posto a sinistra..
        /// </summary>
        internal static string msg_welcome {
            get {
                return ResourceManager.GetString("msg_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorization inserita correttamente.
        /// </summary>
        internal static string succ_categorization_insert {
            get {
                return ResourceManager.GetString("succ_categorization_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorization aggiornata correttamente.
        /// </summary>
        internal static string succ_categorization_update {
            get {
                return ResourceManager.GetString("succ_categorization_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category scheme inserita.
        /// </summary>
        internal static string succ_categoryscheme_insert {
            get {
                return ResourceManager.GetString("succ_categoryscheme_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category scheme aggiornata.
        /// </summary>
        internal static string succ_categoryscheme_update {
            get {
                return ResourceManager.GetString("succ_categoryscheme_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist inserita correttamente.
        /// </summary>
        internal static string succ_codelist_insert {
            get {
                return ResourceManager.GetString("succ_codelist_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codelist aggiornata correttamente.
        /// </summary>
        internal static string succ_codelist_update {
            get {
                return ResourceManager.GetString("succ_codelist_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concetto inserito.
        /// </summary>
        internal static string succ_concept_insert {
            get {
                return ResourceManager.GetString("succ_concept_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concetto aggiornata.
        /// </summary>
        internal static string succ_concept_update {
            get {
                return ResourceManager.GetString("succ_concept_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione riuscita.
        /// </summary>
        internal static string succ_operation {
            get {
                return ResourceManager.GetString("succ_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per effettuare lo spostamento di un category, seleziona la category che vuoi spostare e dopo premi il pulsante &quot;Setta per spostamento&quot;.
        /// </summary>
        internal static string txt_move_instructions_first {
            get {
                return ResourceManager.GetString("txt_move_instructions_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora la category è settata per lo spostamento. Seleziona la category da utilizzare come parent, dopo di che premi il pulsante &quot;Conferma spostamento&quot;. Se premi il pulsante senza avere un parent selezionato, la category verrà spostata a livello di category scheme. Per annullare la procedura premi &quot;Annulla spostamento&quot;..
        /// </summary>
        internal static string txt_move_instructions_second {
            get {
                return ResourceManager.GetString("txt_move_instructions_second", resourceCulture);
            }
        }
    }
}
